#!/usr/bin/python

import numpy as np
import matplotlib.pyplot as plt
import pyfits as pf

def plot_mags(wavelengths = None, mag_list = None, ages = None, limits = None,
        savedir = './', filename = None, show = True, title = '',):

        ''' Plots

        amp_functions = tuple of functions
        '''

        # Import external modules
        import numpy as np
        import pyfits as pf
        import matplotlib.pyplot as plt
        import matplotlib
        from mpl_toolkits.axes_grid1 import ImageGrid

        # Set up plot aesthetics
        plt.clf()
        plt.rcdefaults()
        fontScale = 12
        params = {#'backend': .pdf',
                  'axes.labelsize': fontScale,
                  'axes.titlesize': fontScale,
                  'text.fontsize': fontScale,
                  'legend.fontsize': fontScale*3/4,
                  'xtick.labelsize': fontScale,
                  'ytick.labelsize': fontScale,
                  'font.weight': 500,
                  'axes.labelweight': 500,
                  'text.usetex': False,
                  'figure.figsize': (8, 8),
                 }
        plt.rcParams.update(params)

        # Create figure
        fig = plt.figure()
        grid = ImageGrid(fig, (1,1,1),
                      nrows_ncols=(1,1),
                      ngrids = 1,
                      direction='row',
                      axes_pad=1,
                      aspect=False,
                      share_all=True,
                      label_mode='All')

        colors = ['k','b','g','r','c']
        linestyles = ['-','--','-.','-','-']
        letters = ['a','b']

        for i in range(1):
            ax = grid[i]

            for i, mags in enumerate(mag_list):
                ax.plot(wavelengths, mags,
                        label = 'Age = %s Gyr' % ages[i],
                        )

            if limits is not None:
                ax.set_xlim(limits[0],limits[1])
                ax.set_ylim(limits[2],limits[3])

            # Adjust asthetics
            ax.set_xlabel(r'$\lambda$ (Angstrom)',)
            ax.set_ylabel(r'$M_{AB}$ d$\lambda$')
            ax.grid(True)
            ax.legend(loc='lower right')
            ax.set_title(title)

        if filename is not None:
            plt.savefig(savedir + filename,bbox_inches='tight', dpi=600)
        if show:
            fig.show()

def plot_mass2light(ages = None, m2l = None, limits =
        None, savedir = './', filename = None, show = True, title = '',):

        ''' Plots

        amp_functions = tuple of functions
        '''

        # Import external modules
        import numpy as np
        import pyfits as pf
        import matplotlib.pyplot as plt
        import matplotlib
        from mpl_toolkits.axes_grid1 import ImageGrid

        # Set up plot aesthetics
        plt.clf()
        plt.rcdefaults()
        fontScale = 12
        params = {#'backend': .pdf',
                  'axes.labelsize': fontScale,
                  'axes.titlesize': fontScale,
                  'text.fontsize': fontScale,
                  'legend.fontsize': fontScale*3/4,
                  'xtick.labelsize': fontScale,
                  'ytick.labelsize': fontScale,
                  'font.weight': 500,
                  'axes.labelweight': 500,
                  'text.usetex': False,
                  'figure.figsize': (8, 8),
                 }
        plt.rcParams.update(params)

        # Create figure
        fig = plt.figure()
        grid = ImageGrid(fig, (1,1,1),
                      nrows_ncols=(1,1),
                      ngrids = 1,
                      direction='row',
                      axes_pad=1,
                      aspect=False,
                      share_all=True,
                      label_mode='All')

        colors = ['k','b','g','r','c']
        linestyles = ['-','--','-.','-','-']
        letters = ['a','b']

        for i in range(1):
            ax = grid[i]

            ax.plot(ages, m2l,
                    #label = 'Age = %s Gyr' % ages[i],
                    )

            if limits is not None:
                ax.set_xlim(limits[0],limits[1])
                ax.set_ylim(limits[2],limits[3])

            # Adjust asthetics
            #ax.set_xscale('log')
            ax.set_xlabel(r'Age (Gyr)',)
            ax.set_ylabel(r'$M / L (M_\odot / L_\odot$)')
            ax.grid(True)
            ax.legend(loc='lower right')
            ax.set_title(title)

        if filename is not None:
            plt.savefig(savedir + filename,bbox_inches='tight', dpi=600)
        if show:
            fig.show()

def plot_fluxes(wavelengths = None, flux_list = None, ages = None, metals =
        None, limits = None, savedir = './', filename = None, show = True,
        title = '', log_scale = (1,1), normalized = True, attenuations = None):

        ''' Plots

        amp_functions = tuple of functions
        '''

        # Import external modules
        import numpy as np
        import pyfits as pf
        import matplotlib.pyplot as plt
        import matplotlib
        from mpl_toolkits.axes_grid1 import ImageGrid

        # Set up plot aesthetics
        plt.clf()
        plt.rcdefaults()
        fontScale = 12
        params = {#'backend': .pdf',
                  'axes.labelsize': fontScale,
                  'axes.titlesize': fontScale,
                  'text.fontsize': fontScale,
                  'legend.fontsize': fontScale*3/4,
                  'xtick.labelsize': fontScale,
                  'ytick.labelsize': fontScale,
                  'font.weight': 500,
                  'axes.labelweight': 500,
                  'text.usetex': False,
                  'figure.figsize': (8, 8),
                 }
        plt.rcParams.update(params)

        # Create figure
        fig = plt.figure()
        grid = ImageGrid(fig, (1,1,1),
                      nrows_ncols=(1,1),
                      ngrids = 1,
                      direction='row',
                      axes_pad=1,
                      aspect=False,
                      share_all=True,
                      label_mode='All')

        colors = ['k','b','g','r','c']
        linestyles = ['-','--','-.','-','-']
        letters = ['a','b']

        for i in range(1):
            ax = grid[i]

            for i, fluxes in enumerate(flux_list):
                if ages is not None and metals is None:
                    ax.plot(wavelengths, fluxes,
                            label = 'Age = %.1f Gyr' % ages[i],
                            )
                elif metals is not None and ages is None:
                    ax.plot(wavelengths, fluxes,
                            label = r'Z = %s $\odot$' % metals[i],
                            )
                elif ages is not None and metals is not None:
                    ax.plot(wavelengths, fluxes,
                            label = 'Age = %.1f Gyr, Z = %s $\odot$' % \
                                    (ages[i], metals[i]),
                            )
                elif attenuations is not None:
                    ax.plot(wavelengths, fluxes,
                            label = r'$A_V = $ %s' % attenuations[i],
                            )

            if limits is not None:
                ax.set_xlim(limits[0],limits[1])
                ax.set_ylim(limits[2],limits[3])

            # Adjust asthetics
            if log_scale[0]:
                ax.set_xscale('log')
            if log_scale[1]:
                ax.set_yscale('log')
            ax.set_xlabel(r'$\lambda (\AA$)',)
            if normalized:
                ax.set_ylabel(r'$f_\lambda / f_{5500 \AA}$')
            else:
                ax.set_ylabel(r'$f_\lambda d\lambda$')

            ax.grid(True)
            ax.legend(loc='lower right')
            ax.set_title(title)

        if filename is not None:
            plt.savefig(savedir + filename,bbox_inches='tight', dpi=600)
        if show:
            fig.show()

def attenuate_flux(fluxes, wavelengths, Av):

    tau_v = Av / 1.086

    tau_d = tau_v * (wavelengths / 5500)**-0.7

    fluxes_attenuated = fluxes * np.exp(-tau_d)

    return fluxes_attenuated

def calc_flux2mag(flux):

    # Flux in erg s^-1 cm^-2 Hz^-1

    mag = -2.5 * np.log10(flux / 3.6308e-20)

    return mag

def calc_m2M(mag, distance):
    distance *= 3.24077929e-19 # cm to parsecs

    return mag - 5 * np.log10(distance / 10.)

def calc_z2dist(z):

    # c*z = H_0 * D where H_0 = 70 km / s / Mpc = 0.07 m / s / m

    c = 2.99e8 # m/s
    H_0 = 0.07 # m / s / m

    dist = c*z / H_0

    return dist

def problem_1(section = 'a'):
    #########
    # 1a
    #########

    columns = ['AGE', 'WAVE', 'FLUX']

    f = pf.open('bc03_padova1994_chab_%s_ssp.fit' % 'z02')

    f_data = f[1].data

    ages = np.squeeze(f_data[columns[0]])
    wavelengths = np.squeeze(f_data[columns[1]])
    fluxes = np.squeeze(f_data[columns[2]])

    # assume a distance of 10 pc
    distance = 10 / 3.24077929e-19 # cm

    fluxes_cgs = fluxes / (4 * np.pi * distance**2) * 3.839e33

    mag_ab = -2.5 * np.log10(fluxes_cgs / 3.6308e-20)

    Mags_ab = calc_m2M(mag_ab, distance)

    age_list = (0.001, 0.01, 0.1, 0.3, 0.5, 1, 5, 10)

    Mag_list = []
    for age in age_list:
        age_indices = np.argmin(np.abs(ages - age*1e9))
        Mags = Mags_ab[age_indices]
        Mag_list.append(Mags)

    if section == 'a':
        plot_mags(wavelengths = wavelengths, mag_list = Mag_list,
                ages = age_list,
                limits = (900, 25000, -15, -40),
                savedir = './', filename = 'p_1a.png',
                show = False, title = 'Problem 1a: SSPs')

    #########
    # 1b
    #########

    wavelength_index = np.argmin(np.abs(wavelengths - 5500))

    m2l = 1 / (fluxes[:, wavelength_index] * 5500.)

    if section == 'b':
        plot_mass2light(m2l = m2l,
                ages = ages / 1e9,
                #limits = (10**-2, 10**0, 0, 10**23),
                savedir = './', filename = 'p_1b.png',
                show = False, title = 'Problem 1b: SSP Mass to Light Ratios')

    #########
    # 1c
    #########

    flux_norm_list = []

    for age in age_list:
        age_indices = np.argmin(np.abs(ages - age*1e9))
        flux_norm = fluxes[age_indices] / fluxes[age_indices, wavelength_index]
        flux_norm_list.append(flux_norm)

    if section == 'c':
        plot_fluxes(flux_list = flux_norm_list,
                wavelengths = wavelengths,
                ages = age_list,
                limits = (900, 25000, 10**-4, 500),
                savedir = './', filename = 'p_1c.png',
                show = False, title = 'Problem 1c: SSP Normalized Spectra')

def problem_2(section = 'a'):

    #########
    # 2a
    #########

    data_names = ['z004', 'z05', 'z02']
    metallicities = [0.4, 5, 2]

    columns = ['AGE', 'WAVE', 'FLUX']

    # columns = ['Age', 'Wavelength', 'Flux']

    data = {}

    for i, name in enumerate(data_names):
        f = pf.open('bc03_padova1994_chab_%s_ssp.fit' % name)

        f_data = f[1].data

        data[name] = {'Z': metallicities[i],
                      'ages': np.squeeze(f_data[columns[0]]),
                      'wavelengths': np.squeeze(f_data[columns[1]]),
                      'fluxes': np.squeeze(f_data[columns[2]]),
                      }

    flux_norm_list = []
    wavelengths = data['z004']['wavelengths']
    ages = data['z004']['ages']
    wavelength_index = np.argmin(np.abs(wavelengths - 5500))

    age_index = np.argmin(np.abs(ages - 5*1e6))

    for i, metal in enumerate(data):
    	flux_norm = data[metal]['fluxes'][age_index]
    	flux_norm /= flux_norm[wavelength_index]

    	flux_norm_list.append(flux_norm)

    if section == 'a':
        plot_fluxes(flux_list = flux_norm_list,
                wavelengths = wavelengths,
                metals = metallicities,
                limits = (3500, 7000, 10**-1, 8),
                savedir = './', filename = 'p_2a.png',
                show = False, title = 'Problem 2a: SSP Normalized Spectra')

    #########
    # 2b
    #########

    ''' Find the age at which the high metallicity model best matches the 5 Gry
    old solar Z model.  Compare models normalized at 5500 and evaluate the fit
    over 3500 - 7000 . Do the same A A thing for the low metallicity model and
    plot then all three models together from 3500-7000 .  A On average, how
    large are the residuals? (1%, 10%, 20%?) '''

    age_index_solar = np.argmin(np.abs(ages - 5*1e9))
    wavelength_indices = np.where((wavelengths > 3500) & (wavelengths < 7000))
    wavelength_index = np.argmin(np.abs(wavelengths[wavelength_indices] - 5500))
    flux_z02 = (data['z02']['fluxes'][age_index_solar, wavelength_indices])[0]
    flux_norm_z02 = flux_z02 / flux_z02[wavelength_index]

    flux_norm_z02 = np.ma.array(flux_norm_z02,
            mask=(flux_norm_z02 != flux_norm_z02))

    residuals_array_z05 = np.zeros(len(ages))
    residuals_array_z004 = np.zeros(len(ages))

    for i in range(len(ages)):
    	flux_z05 = (data['z05']['fluxes'][i, wavelength_indices])[0]
    	flux_z004 = (data['z004']['fluxes'][i, wavelength_indices])[0]

        flux_norm_z05 = flux_z05 / flux_z05[wavelength_index]
        flux_norm_z004 = flux_z004 / flux_z004[wavelength_index]

        # mask NaNs
        flux_norm_z05 = np.ma.array(flux_norm_z05,
                mask=(flux_norm_z05 != flux_norm_z05))
        flux_norm_z004 = np.ma.array(flux_norm_z004,
                mask=(flux_norm_z004 != flux_norm_z004))

        residual = np.sum(((flux_norm_z05)**2 - (flux_norm_z02)**2)**0.5)
        residuals_array_z05[i] = residual

        residual = np.sum(((flux_norm_z004)**2 - (flux_norm_z02)**2)**0.5)
        residuals_array_z004[i] = residual

    residuals_array_z05 = np.ma.array(residuals_array_z05,
            mask=(residuals_array_z05 != residuals_array_z05))
    residuals_array_z004 = np.ma.array(residuals_array_z004,
            mask=(residuals_array_z004 != residuals_array_z004))

    age_index_z05 = np.where(residuals_array_z05 == residuals_array_z05.min())
    age_index_z004 = np.where(residuals_array_z004 == \
            residuals_array_z004.min())

    age_indices = [age_index_solar, age_index_z05[0], age_index_z004[0]]

    age_list = [5, ages[age_index_z05][0]/1e9, ages[age_index_z004][0]/1e9]

    metals = ['z02', 'z05', 'z004']
    metals_list = [2, 5, 0.4]
    flux_norm_list = []

    for i, metal in enumerate(metals):
        flux_norm = np.squeeze(data[metal]['fluxes'][age_indices[i],:])
    	flux_norm /= flux_norm[wavelength_index]
    	flux_norm_list.append(flux_norm)

    if section == 'b':
        plot_fluxes(flux_list = flux_norm_list,
                wavelengths = wavelengths,
                ages = age_list,
                metals = metals_list,
                log_scale = (0, 0),
                limits = (3500, 7000, 0, 2),
                savedir = './', filename = 'p_2b.png',
                show = False, title = 'Problem 2b: SSP Normalized Spectra')

    #########
    # 2c
    #########

    if section == 'c':
        plot_fluxes(flux_list = flux_norm_list,
                wavelengths = wavelengths,
                ages = age_list,
                metals = metals_list,
                log_scale = (1, 1),
                limits = (900, 30000, 10**-3, 2),
                savedir = './', filename = 'p_2c.png',
                show = False, title = 'Problem 2c: SSP Normalized Spectra')

def problem_3(section = 'a'):
    #########
    # 3a
    #########

    data_names = ['z004', 'z05', 'z02']
    metallicities = [0.4, 5, 2]

    columns = ['AGE', 'WAVE', 'FLUX']

    # columns = ['Age', 'Wavelength', 'Flux']

    data = {}

    for i, name in enumerate(data_names):
        f = pf.open('bc03_padova1994_chab_%s_ssp.fit' % name)

        f_data = f[1].data

        data[name] = {'Z': metallicities[i],
                      'ages': np.squeeze(f_data[columns[0]]),
                      'wavelengths': np.squeeze(f_data[columns[1]]),
                      'fluxes': np.squeeze(f_data[columns[2]]),
                      }

    flux_norm_list = []
    wavelengths = data['z02']['wavelengths']
    ages = data['z02']['ages']
    fluxes = data['z02']['fluxes']
    wavelength_index = np.argmin(np.abs(wavelengths - 5500))

    age_index = np.argmin(np.abs(ages - 1*1e6))

    flux_list = []
    Av_list = [0.2, 0.5, 1]
    age_index = np.argmin(np.abs(ages - 1*1e6))

    for Av in Av_list:
        fluxes_attenuated = attenuate_flux(fluxes[age_index], wavelengths, Av)
        flux_list.append(fluxes_attenuated)

    if section == 'a':
        plot_fluxes(flux_list = flux_list,
                wavelengths = wavelengths,
                attenuations = Av_list,
                normalized = False,
                log_scale = (0, 1),
                limits = (900, 30000, 10**-6, 1),
                savedir = './', filename = 'p_3a.png',
                show = False, title = 'Problem 3a: SSP Normalized Spectra')


    #########
    # 3b
    #########

    Av = 0.5
    fluxes_solar = flux_list[1]

    wavelength_indices = np.where((wavelengths > 3500) & (wavelengths < 7000))
    flux_z02 = (data['z02']['fluxes'][age_index_solar, wavelength_indices])[0]

    flux_z02 = np.ma.array(flux_z02,
            mask=(flux_z02 != flux_z02))

    residuals_array_z05 = np.zeros(len(ages))
    residuals_array_z004 = np.zeros(len(ages))

    for i in range(len(ages)):
    	flux_z05 = (data['z05']['fluxes'][i, wavelength_indices])[0]
    	flux_z004 = (data['z004']['fluxes'][i, wavelength_indices])[0]

        # mask NaNs
        flux_z05 = np.ma.array(flux_z05,
                mask=(flux_z05 != flux_z05))
        flux_z004 = np.ma.array(flux_z004,
                mask=(flux_z004 != flux_z004))

        residual = np.sum(((flux_z05)**2 - (flux_z02)**2)**0.5)
        residuals_array_z05[i] = residual

        residual = np.sum(((flux_z004)**2 - (flux_z02)**2)**0.5)
        residuals_array_z004[i] = residual

    residuals_array_z05 = np.ma.array(residuals_array_z05,
            mask=(residuals_array_z05 != residuals_array_z05))
    residuals_array_z004 = np.ma.array(residuals_array_z004,
            mask=(residuals_array_z004 != residuals_array_z004))

    age_index_z05 = np.where(residuals_array_z05 == residuals_array_z05.min())
    age_index_z004 = np.where(residuals_array_z004 == \
            residuals_array_z004.min())

    age_indices = [age_index_solar, age_index_z05[0], age_index_z004[0]]

    age_list = [1e-3, ages[age_index_z05][0]/1e9, ages[age_index_z004][0]/1e9]

    metals = ['z02', 'z05', 'z004']
    metals_list = [2, 5, 0.4]
    flux_list = []

    for i, metal in enumerate(metals):
        flux = np.squeeze(data[metal]['fluxes'][age_indices[i], :])
    	flux_list.append(flux)

    if section == 'b':
        plot_fluxes(flux_list = flux_list,
                wavelengths = wavelengths,
                ages = age_list,
                metals = metals_list,
                log_scale = (0, 0),
                limits = (900, 30000, 0, 2),
                savedir = './', filename = 'p_3b.png',
                show = False, title = 'Problem 3b: SSP Spectra')


def main():
    #problem_1(section = 'a')
    #problem_1(section = 'b')
    #problem_1(section = 'c')
    #problem_1(section = 'd')

    #problem_2(section = 'a')
    #problem_2(section = 'b')
    #problem_2(section = 'c')

    problem_3(section = 'a')

if __name__ == '__main__':
    main()




